analyzers:
  sensors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Sensors
    analyzers:
      imu:
        type: diagnostic_aggregator/GenericAnalyzer
        path: imu
        timeout: 5.0
        startswith: imu
        find_and_remove_prefix: imu imu_hardware_interface_node
        num_items: 6
