motor_joints:
  robot_movement_joints:
    left_front_joint: &movement_left_front_joint p3at_front_left_wheel_joint
    right_front_joint: &movement_right_front_joint p3at_front_right_wheel_joint
    left_rear_joint: &movement_left_rear_joint p3at_back_left_wheel_joint
    right_rear_joint: &movement_right_rear_joint p3at_back_right_wheel_joint

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

skid_steer_drive_controller:
  type: pandora_motor/SkidSteerDriveController
  wheel_separation: 0.4
  wheel_radius: 0.11
  max_angular_velocity: 2
  joints:
    - *movement_left_front_joint
    - *movement_right_front_joint
    - *movement_left_rear_joint
    - *movement_right_rear_joint
