# Joint Order:  1.left front, 2.left rear, 3.right front, 4.right rear
# joints must always be listed in the above order
wheel_drive_joints:
  names:
    - left_front_wheel_drive_joint
    - left_rear_wheel_drive_joint
    - right_front_wheel_drive_joint
    - right_rear_wheel_drive_joint
  limits:
    min_velocity: -1.0 # [m/s]
    max_velocity: 1.0 # [m/s]

wheel_steer_joints:
  names:
    - left_front_wheel_steer_joint
    - left_rear_wheel_steer_joint
    - right_front_wheel_steer_joint
    - right_rear_wheel_steer_joint
  limits:
    min_position: deg(-22.5)
    max_position: deg(22.5)

drive_motors:
  motor_controller_names:
    - drive_shaft_motor_controller # motor joint connected to all wheels
  ratios:  # <- final drive ratios of motors
  # gearbox_ratio = 66
  # transmission_ratio = 1.68
  # gear_ratio=spur_ratio/pinion_ratio = 81/60 = 1.35
  # differential_ratio = 3.3
  # final_drive_ratio = 66 * 1.68 * 1.35 * 3.3 = 494
    - 590.4  # measured via experiment
  min_rpms:  # [rpm] (min wheel rpm: -30rpm)
    - -18000.0
  max_rpms:  # [rpm] (max wheel rpm: 30rpm)
    - 18000.0

steer_actuators:
  joint_names:
    - front_steer_actuator_joint
    - rear_steer_actuator_joint
  command_topics:
    - /front_steer_controller/command
    - /rear_steer_controller/command
  joint_state_topics:
    - /front_steer_controller/state
    - /rear_steer_controller/state
  min_position:
    - deg(-45) # -45 degrees or -0.7854 rad
    - deg(-45) # -45 degrees or -0.7854 rad
  max_position: # [rads]
    - deg(45)  # 45 degrees or 0.7854 rad
    - deg(45)  # 45 degrees or 0.7854 rad

steer_mechanism:
  polynomial_approximation_coefficients:
    # left to right steer angle wheel polynomial coefficients
    p_lf_to_rf: [0.0126, -0.0432, 0.0067, -0.0851, 0.9997, 0.0035]
    # right to left steer angle polynomial coefficients
    p_rr_to_lr: [0.0126, -0.0432, 0.0067, -0.0851, 0.9997, 0.0035]
    # left front steer angle to front actuator steer angle
    p_lf_to_fa: [0.5334, 0.2997, 0.2857, 1.4951, 0.0001]
    # right rear steer agle to rear actuator steer angle
    p_rr_to_ra: [0.4225, -0.0959, 0.2930, 0.0668, 1.4949, 0.0]
    # front actuator to left front steer angle
    p_fa_to_lf: [-0.0082, -0.0162, -0.00605, -0.0192, 0.6691, 0.0]
    # rear actuator to right rear steer angle
    p_ra_to_rr: [-0.0104, 0.0173, -0.0604, -0.0193, 0.6691, 0.0]
