skid_steer_drive_controller:
  type: pandora_motor/SkidSteerDriveController
  left_front_wheel: left_front_wheel_joint
  right_front_wheel: right_front_wheel_joint
  left_rear_wheel: left_rear_wheel_joint
  right_rear_wheel: right_rear_wheel_joint
  publish_rate: 50
  wheel_separation_multiplier: 1
  wheel_radius_multiplier: 1
  wheel_radius: 0.0975
  cmd_vel_timeout: 3
  base_frame_id: base_link
  linear:
    x:
      has_velocity_limits: false
      has_acceleration_limits: false
      max_velocity: 0.5
      min_velocity: -0.5
      max_acceleration: 1
      min_acceleration: 1
  angular:
    z:
      has_velocity_limits: false
      has_acceleration_limits: false
      max_velocity: 0.8
      min_velocity: -0.8
      max_acceleration: 1
      min_acceleration: 1
  pose_covariance_diagonal:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  twist_covariance_diagonal:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  linear_fit_degree: 5
  angular_fit_degree: 7
  measured_linear_velocities:
    - expected: 0.10
      actual: 0.10000
    - expected: 0.25
      actual: 0.25000
    - expected: 0.50
      actual: 0.50000
    - expected: -0.10
      actual: -0.10000
    - expected: -0.25
      actual: -0.25000
    - expected: -0.50
      actual: -0.50000
    - expected: 0.00
      actual: 0.00000
  measured_angular_velocities:
    - expected: 1.25
      actual: 0.60531
    - expected: 1.00
      actual: 0.49087
    - expected: 0.75
      actual: 0.36950
    - expected: 0.50
      actual: 0.24500
    - expected: 0.30
      actual: 0.14279
    - expected: 0.25
      actual: 0.12022
    - expected: 0.20
      actual: 0.09239
    - expected: 0.15
      actual: 0.07139
    - expected: 0.10
      actual: 0.04759
    - expected: 0.05
      actual: 0.02345
    - expected: 0.02
      actual: 0.00937
    - expected: -1.25
      actual: -0.60531
    - expected: -1.00
      actual: -0.49087
    - expected: -0.75
      actual: -0.36950
    - expected: -0.50
      actual: -0.24500
    - expected: -0.30
      actual: -0.14279
    - expected: -0.25
      actual: -0.12022
    - expected: -0.20
      actual: -0.09239
    - expected: -0.15
      actual: -0.07139
    - expected: -0.10
      actual: -0.04759
    - expected: -0.05
      actual: -0.02345
    - expected: -0.02
      actual: -0.00937
    - expected: 0.00
      actual: 0.00000
