skid_steer_velocity_controller:
  type: pandora_motor/SkidSteerVelocityController
  left_front_wheel: left_front_wheel_joint
  right_front_wheel: right_front_wheel_joint
  left_rear_wheel: left_rear_wheel_joint
  right_rear_wheel: right_rear_wheel_joint
  publish_rate: 50
  wheel_radius: 0.0922
  track: 0.344
  terrain_parameter: 1.0
  linear_fit_degree: 5
  angular_fit_degree: 7

  # Low friction measurements
  measured_linear_velocities:
  - expected: 0.00
    actual: 0.00000
  measured_angular_velocities:
  - expected: 1.25
    actual: 0.60531
  - expected: 1.00
    actual: 0.49087
  - expected: 0.75
    actual: 0.36950
  - expected: 0.50
    actual: 0.24500
  - expected: 0.30
    actual: 0.14279
  - expected: 0.25
    actual: 0.12022
  - expected: 0.20
    actual: 0.09239
  - expected: 0.15
    actual: 0.07139
  - expected: 0.10
    actual: 0.04759
  - expected: 0.05
    actual: 0.02345
  - expected: 0.02
    actual: 0.00937
  - expected: -1.25
    actual: -0.60531
  - expected: -1.00
    actual: -0.49087
  - expected: -0.75
    actual: -0.36950
  - expected: -0.50
    actual: -0.24500
  - expected: -0.30
    actual: -0.14279
  - expected: -0.25
    actual: -0.12022
  - expected: -0.20
    actual: -0.09239
  - expected: -0.15
    actual: -0.07139
  - expected: -0.10
    actual: -0.04759
  - expected: -0.05
    actual: -0.02345
  - expected: -0.02
    actual: -0.00937
  - expected: 0.00
    actual: 0.00000

  # High friction measurements
  # measured_linear_velocities:
  # - expected: 0.00
  #   actual: 0.00000
  # measured_angular_velocities:
  # - expected: 2.75
  #   actual: 1.06494
  # - expected: 2.50
  #   actual: 1.04719
  # - expected: 2.00
  #   actual: 1.01341
  # - expected: 1.50
  #   actual: 0.78539
  # - expected: 1.25
  #   actual: 0.66842
  # - expected: 1.00
  #   actual: 0.54165
  # - expected: 0.75
  #   actual: 0.37850
  # - expected: 0.50
  #   actual: 0.25750
  # - expected: 0.40
  #   actual: 0.21084
  # - expected: 0.20
  #   actual: 0.10334
  # - expected: 0.10
  #   actual: 0.04970
  # - expected: 0.05
  #   actual: 0.02513
  # - expected: 0.02
  #   actual: 0.01003
  # - expected: 0.01
  #   actual: 0.00482
  # - expected: 0.00
  #   actual: 0.00000
