joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

monstertruck_steer_drive_controller:
  type: monstertruck_steer_drive_controller/MonstertruckSteerDriveController
  publish_rate: 50

  wheel_radius: 0.075  # [m]
  wheelbase: 0.32  # [m]
  track: 0.26  # [m]

  # command_message_type: Twist
  # command_topic: /cmd_vel
  command_message_type: AckermannDrive
  command_topic: /ackermann_cmd

  wheel_joints:
    left:
      front: left_front_wheel_drive_joint
      rear: left_rear_wheel_drive_joint
    right:
      front: right_front_wheel_drive_joint
      rear: right_rear_wheel_drive_joint
  steer_joints:
    left:
      front: left_front_wheel_steer_joint
      rear: left_rear_wheel_steer_joint
    right:
      front: right_front_wheel_steer_joint
      rear: right_rear_wheel_steer_joint
