pixy_pitch_joint: &pixy_pitch_joint pixy_pitch_joint
pixy_yaw_joint: &pixy_yaw_joint pixy_yaw_joint

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
pixy_pitch_controller:
  type: position_controllers/JointPositionController
  joint: *pixy_pitch_joint

pixy_yaw_controller:
  type: position_controllers/JointPositionController
  joint: *pixy_yaw_joint
