linear_motor_joint: &linear_motor_joint linear_joint

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
linear_motor_controller:
  type: position_controllers/JointPositionController
  joint: *linear_motor_joint
