co2_sensors:
  - name: '/sensors/co2'
    frame_id: 'co2_frame'
range_sensors:
  - name: '/sensors/left_sonar'
    frame_id: 'left_sonar_frame'
    code: 'L'
    radiation_type: 0
    field_of_view: 1.0472
    min_range: 0.2
    max_range: 4.0
  - name: '/sensors/right_sonar'
    frame_id: 'right_sonar_frame'
    code: 'R'
    radiation_type: 0
    field_of_view: 1.0472
    min_range: 0.2
    max_range: 4.0
batteries:
  - name: '/PSU_battery'
    code: 'S'
    max_voltage: 25.2
  - name: '/motors_battery'
    code: 'M'
    max_voltage: 25.2
