interface:
  deviceName: "EPOS2"
  protocolStackName: "MAXON_RS232"
  interfaceName: "RS232"
  portName: "/dev/ttyS0"
  baudrate: 115200
  timeout: 500
controllers:
  num: 4
  epos2Gateway_id: 1
  node1: 
    id: 1
    index: "right_front_motor_controller"
  node2: 
    id: 2
    index: "right_rear_motor_controller"
  node3: 
    id: 3
    index: "left_front_motor_controller"
  node4: 
    id: 4
    index: "left_rear_motor_controller"

    



