interface:
  deviceName: "EPOS2"
  protocolStackName: "MAXON SERIAL V2"
  interfaceName: "USB"
  portName: "USB0"
  baudrate: 1000000
  timeout: 500
  connection_attempts: 10
controllers:
  epos2Gateway_id: 1
  names: ["right_front_motor_controller", "right_rear_motor_controller",
          "left_front_motor_controller", "left_rear_motor_controller"]
  node_ids: [1, 2, 3, 4]

  # multiply current with current_to_torque_multiplier to get torque
  # divide torque with current_to_torque_multiplier to get current
  current_to_torque_multiplier: 3.7855 #(=33.5 * 113 / 1000)
